const productsData = [
  {
    "Index": "372185_01",
    "Nazwa": "Puma x Chinatown Market Future Rider",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 529
  },
  {
    "Index": "374477_01",
    "Nazwa": "Puma x Chinatown Market Future Rider",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 529
  },
  {
    "Index": "597152_01",
    "Nazwa": "Legginsy PUMA x HELLY HANSEN",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy",
    "Kolor": "czarny, różowy",
    "Zdjęcie produktu": "",
    "Cena": "ok. 189"
  },
  {
    "Index": "597146_15",
    "Nazwa": "Bluza PUMA x HELLY HANSEN",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "różowy, żółty",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "597145_89",
    "Nazwa": "Spodnie dresowe PUMA x HELLY HANSEN Tailored for Sport",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, żółty, biały",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "597144_89",
    "Nazwa": "Męska kurtka dresowa PUMA x HELLY HANSEN Tailored for Sport",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny, żółty, biały",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "372632_01",
    "Nazwa": "Buty sportowe PUMA x HELLY HANSEN Future Rider",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "czarny, żółty, biały",
    "Zdjęcie produktu": "",
    "Cena": 529
  },
  {
    "Index": "373109_01",
    "Nazwa": "Męskie buty sportowe PUMA x HELLY HANSEN RS-X³ Mid",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "czarny, żółty, biały, szary",
    "Zdjęcie produktu": "",
    "Cena": 639
  },
  {
    "Index": "022725_01",
    "Nazwa": "PUMA x HELLY HANSEN Baseball Cap",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, żółty, biały",
    "Zdjęcie produktu": "",
    "Cena": 129
  },
  {
    "Index": "077195_01",
    "Nazwa": "Torba na ramię PUMA x HELLY HANSEN",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, żółty, biały",
    "Zdjęcie produktu": "",
    "Cena": 149
  },
  {
    "Index": "371570_05",
    "Nazwa": "Buty sportowe PUMA RS-X3 Puzzle",
    "Sezon": "FW19",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "biały, niebieski, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "022590_01",
    "Nazwa": "PUMA x RDET Bucket Hat",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "053518_13",
    "Nazwa": "PUMA TR Bottle Sportstyle",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Unisex",
    "Kategoria": "Akcesoria",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 69
  },
  {
    "Index": "075855_27",
    "Nazwa": "PUMA Academy Waist Bag",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, brązowy",
    "Zdjęcie produktu": "",
    "Cena": 89
  },
  {
    "Index": "656685_01",
    "Nazwa": "Studio Lace Strappy Bra L",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Stanik",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "656685_02",
    "Nazwa": "Studio Lace Strappy Bra L",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Stanik",
    "Kolor": "biały, różowy",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "371149_01",
    "Nazwa": "RIDER PLAY ON",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "niebieski, zielony, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "371149_03",
    "Nazwa": "RIDER PLAY ON",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "fioletowy, różowy, pomarańczowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "193131_04",
    "Nazwa": "Ember TRL Wn's",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarny, turkusowy, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "371964_01",
    "Nazwa": "Rider Sandal Game On",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "niebieski, zielony, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "371870_02",
    "Nazwa": "RS-X MASTER",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, niebieski",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "371201_01",
    "Nazwa": "Deva 90's POP Wn's",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, różowy, fioletowy, żółty",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "371394_01",
    "Nazwa": "PUMA x RANDOMEVENT Ralph Sampson Lo",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "biały, niebieski",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "371402_01",
    "Nazwa": "CELL ALIEN RANDOMEVENT",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "biały, kremowy, żółty",
    "Zdjęcie produktu": "",
    "Cena": 579
  },
  {
    "Index": "371476_01",
    "Nazwa": "LQD CELL OMEGA STRIPED KIT",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "niebieski, czarny, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 499
  },
  {
    "Index": "371571_02",
    "Nazwa": "RS 9.8 FRESH",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "niebieski, czarny, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "371640_01",
    "Nazwa": "RS-X3 Plas_Tech Wn's",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, różowy",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "371777_01",
    "Nazwa": "Rise Wn's",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, miętowy",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "371777_02",
    "Nazwa": "Rise Wn's",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, czarny",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "371777_03",
    "Nazwa": "Rise Wn's",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "brązowy, czarny, różowy",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "371870_01",
    "Nazwa": "RS-X MASTER",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarny, turkusowy, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "372563_01",
    "Nazwa": "Cali Glow Wn’s",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, srebrny",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "372708_01",
    "Nazwa": "Nuage Run Cage",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, zielony, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "597042_01",
    "Nazwa": "TFS OG AOP Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "biały, czarny",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "597043_01",
    "Nazwa": "TFS OG AOP Track Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "biały, czarny",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "597046_02",
    "Nazwa": "Avenir Graphic Crew",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "597061_70",
    "Nazwa": "TFS Fashion Lux Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Kurtka",
    "Kolor": "pomarańczowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "597060_01",
    "Nazwa": "TFS OG AOP Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, biały",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "597062_01",
    "Nazwa": "TFS Fashion Unitard",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Kombinezon",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "597066_51",
    "Nazwa": "Evide AOP Tight Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 249
  },
  {
    "Index": "597068_01",
    "Nazwa": "Digital Love Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "597068_95",
    "Nazwa": "Digital Love Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "597069_01",
    "Nazwa": "Digital Love Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "597069_95",
    "Nazwa": "Digital Love Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "597078_51",
    "Nazwa": "Evide AOP Hoody",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 319
  },
  {
    "Index": "597169_01",
    "Nazwa": "PUMA Club Hoody",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "597170_01",
    "Nazwa": "PUMA Club Sweat Pant",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "597886_80",
    "Nazwa": "Recheck Pack Graphic Hoodie",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "pomarańczowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": 289
  },
  {
    "Index": "597887_01",
    "Nazwa": "Recheck Pack Woven Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny, pomarańczowy, biały",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "597888_01",
    "Nazwa": "Recheck Pack Woven Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, pomarańczowy, biały",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "597892_01",
    "Nazwa": "Recheck Pack Crew Sweat Wmns",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "czarny, żółty, biały",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "597898_01",
    "Nazwa": "Recheck Pack Knitted Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 320
  },
  {
    "Index": "597896_01",
    "Nazwa": "Recheck Pack Graphic Pant",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "598115_88",
    "Nazwa": "Cropped Women's Tank Top",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "różowy, niebieski, czarny",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "598116_88",
    "Nazwa": "Sport Tight Bike Short",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy, Spodenki",
    "Kolor": "różowy, niebieski, czarny",
    "Zdjęcie produktu": "",
    "Cena": "ok. 130"
  },
  {
    "Index": "596696_88",
    "Nazwa": "TFS Cropped Half Zip",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "różowy, fluo",
    "Zdjęcie produktu": "",
    "Cena": 289
  },
  {
    "Index": "596473_89",
    "Nazwa": "TFS OG Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "niebieski, zielony, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "596474_89",
    "Nazwa": "TFS OG Track Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "niebieski, zielony, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 329
  },
  {
    "Index": "596464_41",
    "Nazwa": "PUMA TFS Woven Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "biały, niebieski, czerwony, czarny",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "596464_01",
    "Nazwa": "PUMA TFS Woven Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny, różowy",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "596327_32",
    "Nazwa": "Evide Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "miętowy",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "076831_01",
    "Nazwa": "Large Waistbag",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 169
  },
  {
    "Index": "076906_02",
    "Nazwa": "PUMA Deck Waist Bag",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Akcesoria",
    "Kolor": "szary, czarny",
    "Zdjęcie produktu": "",
    "Cena": 89
  },
  {
    "Index": "076959_01",
    "Nazwa": "PUMA x RHUDE Utility Vest",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kamizelka",
    "Kolor": "czarny, niebieski",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "077015_01",
    "Nazwa": "Rider Game On Backpack",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Unisex",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, zielony, niebieski, biały",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "192799_08",
    "Nazwa": "Hybrid Astro",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "granatowy, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 549
  },
  {
    "Index": "192808_07",
    "Nazwa": "Hybrid Astro Wns",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, różowy, turkusowy",
    "Zdjęcie produktu": "",
    "Cena": 549
  },
  {
    "Index": "193032_02",
    "Nazwa": "Zone XT Metal Wn's",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "076627_13",
    "Nazwa": "AT ESS grip bag",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, biały, różowy",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "193036_01",
    "Nazwa": "LQDCELL Shatter TR Wns",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "żółty, niebieski, biały, kremowy",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "193069_03",
    "Nazwa": "H.ST.20",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "granatowy, zielony, czerwony, biały",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "193083_01",
    "Nazwa": "LQDCELL Hydra Wn's",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarny, różowy",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "193102_02",
    "Nazwa": "Speed 600 2",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "czarny, turkusowy, żółty",
    "Zdjęcie produktu": "",
    "Cena": 579
  },
  {
    "Index": "193104_01",
    "Nazwa": "SPEED 300 RACER 2",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "żółty",
    "Zdjęcie produktu": "",
    "Cena": 499
  },
  {
    "Index": "193108_01",
    "Nazwa": "Hybrid NX Ozone FM",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "czarny, żółty, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "193108_02",
    "Nazwa": "Hybrid NX Ozone FM",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "żółty, czarny",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "371389_01",
    "Nazwa": "Cell King RHUDE",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 669
  },
  {
    "Index": "371392_01",
    "Nazwa": "Ralph Sampson Lo RHUDE",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "kremowy",
    "Zdjęcie produktu": "",
    "Cena": 579
  },
  {
    "Index": "371569_05",
    "Nazwa": "RS-X³ PLASTIC GULF STREAM",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "turkusowy, różowy, zielony",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "372884_01",
    "Nazwa": "RS-X3 SUPER",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "biały, czerwony, czarny",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "596660_02",
    "Nazwa": "PUMA x RDET AOP Windbreaker",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "żółty",
    "Zdjęcie produktu": "",
    "Cena": 669
  },
  {
    "Index": "596661_01",
    "Nazwa": "PUMA x RDET Bomber Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 799
  },
  {
    "Index": "596662_50",
    "Nazwa": "PUMA x RDET Hoodie",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "biały, kremowy",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "596666_01",
    "Nazwa": "PUMA x RDET Woven Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "596670_01",
    "Nazwa": "PUMA x RDET Hooded Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "517422_17",
    "Nazwa": "A.C.E. Racerback Tank",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 119
  },
  {
    "Index": "518255_10",
    "Nazwa": "Ignite SS Tee",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 119
  },
  {
    "Index": "518269_04",
    "Nazwa": "Ignite Long Tight",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy",
    "Kolor": "czarny, różowy",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "518958_01",
    "Nazwa": "Runner ID Jacket",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "czarny, zielony",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "519011_03",
    "Nazwa": "The First Mile Tee",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "519014_01",
    "Nazwa": "The First Mile Eclipse Tight",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy",
    "Kolor": "czarny, bordowy",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "519021_03",
    "Nazwa": "First Mile SS Tee",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 189
  },
  {
    "Index": "519022_01",
    "Nazwa": "First Mile 2in1 Woven Pant",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "519024_01",
    "Nazwa": "First Mile Utility Jacket",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "519024_03",
    "Nazwa": "First Mile Utility Jacket",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "brązowy, czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "519026_01",
    "Nazwa": "Graphic Tee",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 119
  },
  {
    "Index": "519034_01",
    "Nazwa": "The First Mile Anorak",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Kurtka",
    "Kolor": "czarny, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "519034_03",
    "Nazwa": "The First Mile Anorak",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Kurtka",
    "Kolor": "turkusowy, różowy",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "519035_02",
    "Nazwa": "The First Mile Tank",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "żółty",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "519036_01",
    "Nazwa": "Metal Splash Splatter Tight",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "519037_01",
    "Nazwa": "Metal Splash Deep V Tee",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "519038_01",
    "Nazwa": "Metal Splash Lux Wrap Hoodie",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 279
  },
  {
    "Index": "519042_01",
    "Nazwa": "Last Lap Cropped Tee",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "różowa",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "519202_02",
    "Nazwa": "First Mile 4Keeps Bra M",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "581308_31",
    "Nazwa": "Rebel Fashion Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "zielony, fluo",
    "Zdjęcie produktu": "",
    "Cena": 99
  },
  {
    "Index": "581308_52",
    "Nazwa": "Rebel Fashion Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 99
  },
  {
    "Index": "581311_51",
    "Nazwa": "Rebel 7\" Short Tight",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy, Spodenki",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 119
  },
  {
    "Index": "581578_01",
    "Nazwa": "Amplified AOP Bodysuit",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Body",
    "Kolor": "czarny, biały",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "581756_01",
    "Nazwa": "ESS+ Fitted Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 159
  },
  {
    "Index": "596094_04",
    "Nazwa": "BMW MMS T7 Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Motorsport",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "niebieski, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "596102_02",
    "Nazwa": "BMW MMS Graphic Tee",
    "Sezon": "SS20",
    "Sektor": "Motorsport",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "596108_01",
    "Nazwa": "BMW MMS Graphic Polo",
    "Sezon": "SS20",
    "Sektor": "Motorsport",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "596258_01",
    "Nazwa": "TFS Graphic Crop Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "596261_01",
    "Nazwa": "TFS Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "596262_32",
    "Nazwa": "TFS Hoody",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "turkusowy, biały",
    "Zdjęcie produktu": "",
    "Cena": 289
  },
  {
    "Index": "596291_32",
    "Nazwa": "TFS Woven Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Kurtka",
    "Kolor": "turkusowy, biały, czarny",
    "Zdjęcie produktu": "",
    "Cena": 329
  },
  {
    "Index": "596292_01",
    "Nazwa": "TFS Legging",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "596294_01",
    "Nazwa": "Classics T7 Pleated Skirt",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Spódnica",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "596299_51",
    "Nazwa": "Evide Crew",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 289
  },
  {
    "Index": "596300_16",
    "Nazwa": "Evide Longsleeve Mesh Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596302_51",
    "Nazwa": "Evide Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Spodnie",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 289
  },
  {
    "Index": "596307_01",
    "Nazwa": "Evide Highwaist Short Tight",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Szorty",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "597198_01",
    "Nazwa": "TFS Industrial Woven Vest",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kamizelka",
    "Kolor": "czarny, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 329
  },
  {
    "Index": "596755_69",
    "Nazwa": "PUMA x RHUDE HZ Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "kremowy, niebieski, brązowy",
    "Zdjęcie produktu": "",
    "Cena": 769
  },
  {
    "Index": "596753_81",
    "Nazwa": "PUMA x RHUDE",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "kremowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": ""
  },
  {
    "Index": "596757_02",
    "Nazwa": "PUMA x RHUDE Graphic Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "596754_81",
    "Nazwa": "PUMA x RHUDE Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, kremowy",
    "Zdjęcie produktu": "",
    "Cena": ""
  },
  {
    "Index": "596704_51",
    "Nazwa": "Evide AOP Crop Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596677_01",
    "Nazwa": "Puma Skirt",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Spódnica",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 249
  },
  {
    "Index": "596475_01",
    "Nazwa": "TFS Industrial Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "czarny, różowy, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "596476_01",
    "Nazwa": "TFS Industrial Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, różowy, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "596472_70",
    "Nazwa": "TFS Industrial Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "596471_51",
    "Nazwa": "TFS OG Track Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Szorty",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "596470_27",
    "Nazwa": "Avenir Woven Track Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "żółty",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "596470_11",
    "Nazwa": "Avenir Woven Track Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "czerwony",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "596470_01",
    "Nazwa": "Avenir Woven Track Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 349
  },
  {
    "Index": "596468_41",
    "Nazwa": "UMA TFS Woven Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "niebieski, czarny",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "596462_01",
    "Nazwa": "Avenir Pants cl",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "596461_27",
    "Nazwa": "Avenir Woven Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "żółty",
    "Zdjęcie produktu": "",
    "Cena": 329
  },
  {
    "Index": "596461_11",
    "Nazwa": "Avenir Woven Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czerwony",
    "Zdjęcie produktu": "",
    "Cena": 329
  },
  {
    "Index": "596459_41",
    "Nazwa": "Avenir Hoody",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "niebieski, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 329
  },
  {
    "Index": "596457_01",
    "Nazwa": "Avenir Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "596445_51",
    "Nazwa": "Iconic MCS Track Pants PT",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "596444_41",
    "Nazwa": "Iconic MCS Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "czerwony, niebieski, biały",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "596444_01",
    "Nazwa": "Iconic MCS Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "czarny, biały",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "596443_02",
    "Nazwa": "Iconic MCS Track Jacket PT",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "niebieski, biały, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "596442_41",
    "Nazwa": "Iconic MCS Crew FT",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Bluza",
    "Kolor": "niebieski, biały, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "596369_32",
    "Nazwa": "Downtown Graphic Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "turkusowy, miętowy",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "596369_02",
    "Nazwa": "Downtown Graphic Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 139
  },
  {
    "Index": "077171_01",
    "Nazwa": "PUMA x First Mile Running Backpack",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Kobieta",
    "Kategoria": "Plecak",
    "Kolor": "czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 249
  },
  {
    "Index": "022692_01",
    "Nazwa": "PUMA x First Mile Running Cap",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Kobieta",
    "Kategoria": "Czapka",
    "Kolor": "czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 99
  },
  {
    "Index": "193031_01",
    "Nazwa": "PUMA Zone XT Men's Training Shoes",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "Czarny, biały",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "193080_01",
    "Nazwa": "PUMA Zone XT Men's Training Shoes",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "Czarny, biały, zółty",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "193080_02",
    "Nazwa": "PUMA Zone XT Men's Training Shoes",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "Czarny, biały, zółty",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "193084_01",
    "Nazwa": "PUMA LQDCELL Hydra Training Shoes",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Buty",
    "Kolor": "Beżowy, brązowy, żółty",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "519021_01",
    "Nazwa": "PUMA x First Mile Training Tee",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "Czarny",
    "Zdjęcie produktu": "",
    "Cena": 189
  },
  {
    "Index": "519021_03",
    "Nazwa": "PUMA x First Mile Training Tee",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Koszulka",
    "Kolor": "pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 189
  },
  {
    "Index": "519022_01",
    "Nazwa": "PUMA x First Mile Training T-shirt",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Spodnie",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "519024_03",
    "Nazwa": "PUMA x First Mile Utility Running Jacket",
    "Sezon": "SS20",
    "Sektor": "Running",
    "Kolekcja": "Mężczyzna",
    "Kategoria": "Kurtka",
    "Kolor": "Beżowy, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "193086_01",
    "Nazwa": "PUMA LQDCELL Hydra Training Shoes",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "Czarny, biały",
    "Zdjęcie produktu": "",
    "Cena": 439
  },
  {
    "Index": "519034_03",
    "Nazwa": "PUMA x First Mile Training Anorak",
    "Sezon": "SS20",
    "Sektor": "Training",
    "Kolekcja": "Kobieta",
    "Kategoria": "Kurtka",
    "Kolor": "Zielony, czarny, pomarańczowy",
    "Zdjęcie produktu": "",
    "Cena": 399
  },
  {
    "Index": "371409_01",
    "Nazwa": "DEVA  CHARLOTTE",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarny, brązowy, czerwony",
    "Zdjęcie produktu": "",
    "Cena": 579
  },
  {
    "Index": "022586_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Bucket Hat",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, brązowy",
    "Zdjęcie produktu": "",
    "Cena": 169
  },
  {
    "Index": "022587_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Cap",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 149
  },
  {
    "Index": "022781_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Visor",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 149
  },
  {
    "Index": "077005_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Shopper",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "transparentny, czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 339
  },
  {
    "Index": "077006_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Waist Bag",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Akcesoria",
    "Kolor": "transparentny, czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "371408_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Cali Sport Women's Trainers",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "białe, czerwone, brązowe, czarne",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "371405_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Love Women's Trainers",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarne, białe",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "372860_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Rise Women's Trainers",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "biały, różowy, złoty",
    "Zdjęcie produktu": "",
    "Cena": 529
  },
  {
    "Index": "371837_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA FTR Women's Leadcat Sandals",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Buty",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "596760_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Tailored for Sport Women's Track Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Spodnie",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "596760_90",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Tailored for Sport Women's Track Pants",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Spodnie",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 369
  },
  {
    "Index": "596761_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Crop Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 199
  },
  {
    "Index": "596761_90_1",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Classics Women's Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "596762_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Classics Women's Dress",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Sukienka",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "596763_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596763_02",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596763_52",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596763_57",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "biały",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596763_90",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Tee",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Koszulka",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 179
  },
  {
    "Index": "596764_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Tights",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Legginsy",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "596765_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Women's Shorts",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Szorty",
    "Kolor": "czarny, złoty",
    "Zdjęcie produktu": "",
    "Cena": 239
  },
  {
    "Index": "596854_02",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Tailored for Sport AOP Women's Track Jacket",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "brązowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": 479
  },
  {
    "Index": "596855_02",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA AOP Women's Crop Top",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Top",
    "Kolor": "brązowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": 219
  },
  {
    "Index": "596856_02",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA AOP Women's Shorts",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Szorty",
    "Kolor": "brązowy, czarny",
    "Zdjęcie produktu": "",
    "Cena": 269
  },
  {
    "Index": "597272_01",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Crew Women's Sweatshirt",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "czarny",
    "Zdjęcie produktu": "",
    "Cena": 299
  },
  {
    "Index": "597272_90",
    "Nazwa": "PUMA x CHARLOTTE OLYMPIA Crew Women's Sweatshirt",
    "Sezon": "SS20",
    "Sektor": "Sportstyle",
    "Kolekcja": "Kobieta",
    "Kategoria": "Bluza",
    "Kolor": "różowy",
    "Zdjęcie produktu": "",
    "Cena": 299
  }
]